name: luinlove
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # UI
  carousel_slider: ^4.2.1
  step_progress_indicator: ^1.0.2
  google_fonts: ^4.0.5

  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # DateTime
  intl: ^0.18.1
  time_machine: ^0.9.17

  # Data class
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

  # Local storage
  shared_preferences: ^2.2.1

  # Firebase
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4
  flutter_local_notifications: ^15.0.1+1

  # Picking image
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Generate class
  # flutter pub run build_runner build --delete-conflicting-outputs
  build_runner: ^2.4.6
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true
  # assets:
  #   - assets/icons/
  #   - assets/images/
  #   - assets/fonts/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
